### PR TITLE
update sources to Bosque v0.5.0-rc-1

### PR DESCRIPTION
**Pull request by brakmic**
Hi,

This PR updates the sources in **BooksAndRecords** and **Orders** to latest Bosque **v0.5.0-rc-1**.

I've kept most of the original code unchanged. A big chunk of fixes deals with syntax errors, but there are also a few changes that are related to Bosque's language design. 

For example, the method Map<K,V>.**add** is not available anymore ([and for good reasons](https://github.com/microsoft/BosqueLanguage/issues/342#issuecomment-645649181)), so that I replaced it with **unionWith**.  I also had to introduce some extra Map-type conversions, because of some [important reasons](https://github.com/microsoft/BosqueLanguage/issues/346#issuecomment-646843899).

All in all, the errors are gone except one that has to do with the **if-else statemens**. But soon [there will be a fix for that](https://github.com/microsoft/BosqueLanguage/issues/286#issuecomment-646424887).

Of course, _feel free to ignore this PR_.

I was using this repo for education purposes only, because there aren't that many Bosque resources available. 

Regards,

### CODE REVIEW

**Comment by AttilaMihaly** [comment]
Thank you for your contribution! We greatly appreciate your efforts! 

One last thing we ask you to do before we can merge your PR is to fill out our contribution agreement. You can find detailed instructions in `CONTRIBUTING.md`. I think it will be easiest if you open a new PR with the `DCO` so that we can merge that before this one is merged.

Thank you and sorry for the extra hassle.

**Comment by brakmic** [comment]
> Thank you for your contribution! We greatly appreciate your efforts!
> 
> One last thing we ask you to do before we can merge your PR is to fill out our contribution agreement. You can find detailed instructions in `CONTRIBUTING.md`. I think it will be easiest if you open a new PR with the `DCO` so that we can merge that before this one is merged.
> 
> Thank you and sorry for the extra hassle.

No problem. I'll open a new PR with the contribution agreement.

**Comment by AttilaMihaly** [comment]
Thanks for adding the DCO. Can you also amend your commit message and add `“Covered by <dco>“` line which indicates your acceptance of the DCO terms and conditions. 
`<dco>` here is the file name of the DCO. Thanks.

**Comment by brakmic** [comment]
> Thanks for adding the DCO. Can you also amend your commit message and add `“Covered by <dco>“` line which indicates your acceptance of the DCO terms and conditions.
> `<dco>` here is the file name of the DCO. Thanks.

Have force pushed the commit.

**Comment by AttilaMihaly** [comment]
Thank you!

**Pull request merged**
